### ISSUE TITLE
About New Instruments

### ISSUE THREAD

**Issue by cangerjun** [Specy/genshin-music#35]
Today, Genshin Impact 4.6 forward-looking live broadcast added a new Instrument, it looks like an french horn

**Comment by Specy** [comment]
Yes I saw, there is one issue for implementing it, which is the instrument is able to be "held down" to play long notes, the app currently has no support for that so I'll have to do a big rework to add that, it's gonna take a while

**Comment by ptr2019** [comment]
> Yes I saw, there is one issue for implementing it, which is the instrument is able to be "held down" to play long notes, the app currently has no support for that so I'll have to do a big rework to add that, it's gonna take a while

That's great >v< Looking forward to the newly implemented instrument. No such implementations or attempts have been found elsewhere. How is it going with the implementation?

**Comment by Specy** [comment]
Right now i'm working to add translations to the app, after that is done i'll start with this

**Comment by cangerjun** [comment]
I see the mode of 'have Do Re Mi' in NOTE NAME tpye. Can you add another numerical version?
1 2 3 4 5 6 7

**Comment by Specy** [comment]
> I see the mode of 'have Do Re Mi' in NOTE NAME tpye. Can you add another numerical version? 1 2 3 4 5 6 7

Sure, would the numbers then repeat? Like 
1 2 3 4 5 6 7 
1 2 3 4 5 6 7 
1 2 3 4 5 6 7
Or would it incrementally continue up to 21?

**Comment by cangerjun** [comment]
Sure, the numbers repeat。

**Comment by cangerjun** [comment]
> Sure, would the numbers then repeat?

Sure, the numbers repeat.、
当然重复啦，我们交流还是用中文吧。
给作者看的留言再用英语吧

**Comment by cangerjun** [comment]
Sure,the numbers repeat。
1 2 3 4 5 6 7
1 2 3 4 5 6 7
1 2 3 4 5 6 7
other request：You can add a national flag before the language for better differentiation.

**Comment by Specy** [comment]
> Sure,the numbers repeat。 1 2 3 4 5 6 7 1 2 3 4 5 6 7 1 2 3 4 5 6 7 other request：You can add a national flag before the language for better differentiation.

Hmmm, wouldn't this layout be confusing? Is it being used by people already or is it something new?

I'll add the flag later

**Comment by cangerjun** [comment]
> > Sure,the numbers repeat。 1 2 3 4 5 6 7 1 2 3 4 5 6 7 1 2 3 4 5 6 7 other request：You can add a national flag before the language for better differentiation.
> 
> Hmmm, wouldn't this layout be confusing? Is it being used by people already or is it something new?
> 
> I'll add the flag later

In Chinese keyboard performance software, numbers are used as key pitch displays.
The difference between 1234567 with different pitches lies in whether there are dots above or below, and how many dots there are.

**Comment by cangerjun** [comment]
There is also a notation system from Europe, which is now called Numbered Musical Notation.
This is my YouTube channe lhttps://www.youtube.com/@NiyasanAnimeonflute
The video I uploaded is the musical score recorded using this notation method.

**Comment by Specy** [comment]
Ok so it would be repeating numbers + dots below, that might be a bit harder to do as I'd have to use icons for the text which is not currently supported, perhaps there is some unicode way to add dots above characters?

**Comment by Specy** [comment]
ok maybe something like this?
 ̥1̥ 
 an issue with numbers is that a single dot appears on the top/bottom right (1̥ ), so i had to add the dot to a "space" behind it, which is not the best solution

**Comment by ptr2019** [comment]
Yeah, I think so. Btw, how about 
adding translation to the "note name" drop down, e.t.c., 
and distinguishing the notes in different octaves with numbers, e.g. "C4" vs "C5", which could be easier than implementation for numbered musical notation mentioned above.
![图片](https://github.com/Specy/genshin-music/assets/56548868/bffa5179-c375-4b53-b6a7-3002b60c3c64)

**Comment by Specy** [comment]
Yes i was looking for places I missed to translate and found a few, I've added them to a list, I won't be home for a few days so I'll continue the work when I come back, also @cangerjun or @ptr2019 can you please create a new issue for this music notes format?

**Comment by ptr2019** [comment]
Ready now, as @cangerjun has done.

**Comment by cangerjun** [comment]
议题已经陈旧，已经有一个同类型议题，这个议题暂时关闭
