### ISSUE TITLE
Fail to build desktop app

### ISSUE THREAD

**Issue by ptr2019** [Specy/genshin-music#51]
Building app for desktop terminates unexpectedly, showing
>Genshin build complete
Build complete
error: unexpected argument './src-tauri/tauri-sky.conf.json' found
Usage: cargo.exe build [OPTIONS]
For more information, try '--help'.
       Error failed to build app: failed to build app

in the end.

It seems that the following command fails
` tauri build ./src-tauri/tauri-sky.conf.json`
(this is printed on the cmd window at the beginning of the building process),
which should be `tauri build --config ./src-tauri/tauri-sky.conf.json`, but I am not sure about how to fix it (this command is not found in the code).

Besides, the command `npm run start` also fails, as there is no corresponding command for `start` in the code.

I am not sure about the reason why this happens. The building process went well for previous release, but something is wrong for this time.

**Comment by Specy** [comment]
I never really finished developing the desktop version of the app as it didn't really bring much benefit, i'd suggest you to use the web version installed as a webapp, it's pretty much the same thing.

**Comment by ptr2019** [comment]
Got it. The good news is that the web version works well, as far as I have tested.
