### ISSUE TITLE
Can’t play fast note

### ISSUE THREAD

**Issue by studiobuttermedia** [Specy/genshin-music#6]
I try to play Do Mi Son but when I try to play it fast, it doesn't register Mi.

**Comment by Specy** [comment]
What's your device name? This most likely is a gesture issue from your device, I sadly can't do much about it but I'll try to address issues whenever I do the main page rewrite in some weeks

**Comment by studiobuttermedia** [comment]
I tested this on 2 iPads, 6th generation iPad, iPad Pro 3rd generation, iPhone 6 Plus, Google Pixel 2. And none of them able to play fast notes

**Comment by Specy** [comment]
Might it be that you have your fingers too close to the buttons so that the phone think you are trying to swipe instead of touch? Try to increase the keyboard size and retest, I just tried and it seems like whenever I have my fingers too close to each other the click doesn't trigger

**Comment by studiobuttermedia** [comment]
It seem to be fix. I was able to play multiple notes at a fast speed.
