### ISSUE TITLE
[QUESTION] How to add long notes for violin for example , 2) why i cant import multiple MIDI files to same melody (each one in a layer)

### ISSUE THREAD

**Issue by TheLime1** [Specy/genshin-music#81]
1) How to add long notes for violin for example 
2) why i cant import multiple MIDI files to same melody (each one in a layer)

**Comment by TheLime1** [comment]
also there is a bug for some long notes instruments (like saxophone) you dont hear anything if you use the sheets because the instrument take 0.5sec to just hear the actual note

**Comment by Specy** [comment]
Long notes are not currently implemented.

MIDI creates a new song rather than adding it to the current one as it could "break" the current song, you can merge multiple midi files to the same melody by creating different songs, then copying the whole song and pasting it into another one
